//! Sync tooling CLI module.
//!
//! Implements `sync generate|list` for `[[sync]]` config in `qail.toml`.

const std = @import("std");
const io_compat = @import("../runtime/io.zig");

const Allocator = std.mem.Allocator;
const print = std.debug.print;
const QAIL_CONFIG_FILE = "qail.toml";
const MIGRATIONS_DIR = "migrations";
const MAX_CONFIG_BYTES = 4 * 1024 * 1024;

const SyncRule = struct {
    source_table: []u8,
    target_collection: []u8,
    trigger_column: ?[]u8 = null,
    embedding_model: ?[]u8 = null,

    fn deinit(self: *SyncRule, allocator: Allocator) void {
        allocator.free(self.source_table);
        allocator.free(self.target_collection);
        if (self.trigger_column) |value| allocator.free(value);
        if (self.embedding_model) |value| allocator.free(value);
        self.trigger_column = null;
        self.embedding_model = null;
    }
};

const SyncRuleBuilder = struct {
    source_table: ?[]u8 = null,
    target_collection: ?[]u8 = null,
    trigger_column: ?[]u8 = null,
    embedding_model: ?[]u8 = null,

    fn deinit(self: *SyncRuleBuilder, allocator: Allocator) void {
        if (self.source_table) |value| allocator.free(value);
        if (self.target_collection) |value| allocator.free(value);
        if (self.trigger_column) |value| allocator.free(value);
        if (self.embedding_model) |value| allocator.free(value);
        self.source_table = null;
        self.target_collection = null;
        self.trigger_column = null;
        self.embedding_model = null;
    }

    fn hasAnyField(self: *const SyncRuleBuilder) bool {
        return self.source_table != null or
            self.target_collection != null or
            self.trigger_column != null or
            self.embedding_model != null;
    }
};

const ParsedConfig = struct {
    project_mode: ?[]u8 = null,
    sync_rules: std.ArrayList(SyncRule) = .empty,

    fn deinit(self: *ParsedConfig, allocator: Allocator) void {
        if (self.project_mode) |value| allocator.free(value);
        self.project_mode = null;
        for (self.sync_rules.items) |*rule| {
            rule.deinit(allocator);
        }
        self.sync_rules.deinit(allocator);
    }
};

const Section = enum {
    none,
    project,
    sync,
    other,
};

pub fn make(comptime Cli: type) type {
    const SyncAction = Cli.SyncAction;
    return struct {
        pub fn runSync(allocator: Allocator, action: SyncAction) !void {
            switch (action) {
                .generate => try generateSyncTriggers(allocator),
                .list => try listSyncRules(allocator),
            }
        }
    };
}

const KeyValue = struct {
    key: []const u8,
    value: []const u8,
};

const TableHeader = struct {
    is_array: bool,
    name: []const u8,
};

pub fn generateSyncTriggers(allocator: Allocator) !void {
    try generateSyncTriggersAt(allocator, ".");
}

pub fn listSyncRules(allocator: Allocator) !void {
    try listSyncRulesAt(allocator, ".");
}

fn generateSyncTriggersAt(allocator: Allocator, root: []const u8) !void {
    var config = try loadQailConfig(allocator, root);
    defer config.deinit(allocator);

    if (!isHybridProject(config.project_mode)) {
        print("Sync triggers only apply to project.mode = \"hybrid\".\n", .{});
        return error.InvalidProjectMode;
    }

    if (config.sync_rules.items.len == 0) {
        print("No [[sync]] rules found in {s}\n", .{QAIL_CONFIG_FILE});
        print("Add sync rules like:\n", .{});
        print("  [[sync]]\n", .{});
        print("  source_table = \"products\"\n", .{});
        print("  trigger_column = \"description\"\n", .{});
        print("  target_collection = \"products_search\"\n", .{});
        return;
    }

    const migrations_dir = try joinPath(allocator, root, MIGRATIONS_DIR);
    defer allocator.free(migrations_dir);

    const io_iface = io_compat.runtimeIo();
    try std.Io.Dir.cwd().createDirPath(io_iface, migrations_dir);

    const next_sequence = try findNextMigrationSequence(migrations_dir);
    const seq = try formatSequence(allocator, next_sequence);
    defer allocator.free(seq);

    const up_path = try std.fmt.allocPrint(
        allocator,
        "{s}/{s}_qail_sync_triggers.up.qail",
        .{ migrations_dir, seq },
    );
    defer allocator.free(up_path);

    const down_path = try std.fmt.allocPrint(
        allocator,
        "{s}/{s}_qail_sync_triggers.down.qail",
        .{ migrations_dir, seq },
    );
    defer allocator.free(down_path);

    var up_content: std.ArrayList(u8) = .empty;
    defer up_content.deinit(allocator);
    try up_content.appendSlice(
        allocator,
        "# QAIL Sync Triggers\n# Auto-generated by: qail sync generate\n\n",
    );

    for (config.sync_rules.items) |*rule| {
        try appendSyncRuleUp(allocator, &up_content, rule);
    }

    var down_content: std.ArrayList(u8) = .empty;
    defer down_content.deinit(allocator);
    try down_content.appendSlice(allocator, "# QAIL Sync Triggers - Rollback\n\n");

    var idx = config.sync_rules.items.len;
    while (idx > 0) : (idx -= 1) {
        try appendSyncRuleDown(allocator, &down_content, &config.sync_rules.items[idx - 1]);
    }

    try writeFileAll(up_path, up_content.items);
    try writeFileAll(down_path, down_content.items);

    print("Created {s}\n", .{up_path});
    print("Created {s}\n", .{down_path});
    print("Next: run 'qail migrate up' to apply triggers.\n", .{});
}

fn listSyncRulesAt(allocator: Allocator, root: []const u8) !void {
    var config = try loadQailConfig(allocator, root);
    defer config.deinit(allocator);

    if (config.sync_rules.items.len == 0) {
        print("No sync rules configured.\n", .{});
        return;
    }

    const mode = config.project_mode orelse "unset";
    print("Sync Rules ({d}) [project.mode={s}]\n", .{ config.sync_rules.items.len, mode });
    for (config.sync_rules.items, 0..) |rule, i| {
        print("  {d}. {s} -> {s}\n", .{ i + 1, rule.source_table, rule.target_collection });
        if (rule.trigger_column) |column| {
            print("     trigger_column: {s}\n", .{column});
        }
        if (rule.embedding_model) |model| {
            print("     embedding_model: {s}\n", .{model});
        }
    }
}

fn loadQailConfig(allocator: Allocator, root: []const u8) !ParsedConfig {
    const config_path = try joinPath(allocator, root, QAIL_CONFIG_FILE);
    defer allocator.free(config_path);

    const raw = try readFileAlloc(allocator, config_path, MAX_CONFIG_BYTES);
    defer allocator.free(raw);

    return parseQailToml(allocator, raw);
}

fn parseQailToml(allocator: Allocator, raw: []const u8) !ParsedConfig {
    var config = ParsedConfig{
        .project_mode = null,
        .sync_rules = .empty,
    };
    errdefer config.deinit(allocator);

    var section: Section = .none;
    var current_sync: ?SyncRuleBuilder = null;
    errdefer if (current_sync) |*rule| rule.deinit(allocator);

    var lines = std.mem.splitScalar(u8, raw, '\n');
    while (lines.next()) |line_raw| {
        const line_no_comment = stripInlineComment(line_raw);
        const line = std.mem.trim(u8, line_no_comment, " \t\r");
        if (line.len == 0) continue;

        if (parseTableHeader(line)) |header| {
            if (header.is_array and std.ascii.eqlIgnoreCase(header.name, "sync")) {
                try flushCurrentSyncRule(allocator, &config, &current_sync);
                current_sync = SyncRuleBuilder{};
                section = .sync;
                continue;
            }

            if (section == .sync) {
                try flushCurrentSyncRule(allocator, &config, &current_sync);
            }

            if (!header.is_array and std.ascii.eqlIgnoreCase(header.name, "project")) {
                section = .project;
            } else if (!header.is_array and std.ascii.eqlIgnoreCase(header.name, "sync")) {
                if (current_sync == null) current_sync = SyncRuleBuilder{};
                section = .sync;
            } else {
                section = .other;
            }
            continue;
        }

        const kv = splitKeyValue(line) orelse continue;
        const parsed_value = try parseTomlStringLike(allocator, kv.value);
        var value_assigned = false;

        switch (section) {
            .project => {
                if (std.mem.eql(u8, kv.key, "mode")) {
                    replaceOwnedField(allocator, &config.project_mode, parsed_value);
                    value_assigned = true;
                }
            },
            .sync => {
                if (current_sync == null) current_sync = SyncRuleBuilder{};
                var rule = &current_sync.?;
                if (std.mem.eql(u8, kv.key, "source_table")) {
                    replaceOwnedField(allocator, &rule.source_table, parsed_value);
                    value_assigned = true;
                }
                if (std.mem.eql(u8, kv.key, "target_collection")) {
                    replaceOwnedField(allocator, &rule.target_collection, parsed_value);
                    value_assigned = true;
                }
                if (std.mem.eql(u8, kv.key, "trigger_column")) {
                    replaceOwnedField(allocator, &rule.trigger_column, parsed_value);
                    value_assigned = true;
                }
                if (std.mem.eql(u8, kv.key, "embedding_model")) {
                    replaceOwnedField(allocator, &rule.embedding_model, parsed_value);
                    value_assigned = true;
                }
            },
            .none, .other => {
                if (std.mem.eql(u8, kv.key, "project.mode")) {
                    replaceOwnedField(allocator, &config.project_mode, parsed_value);
                    value_assigned = true;
                }
            },
        }

        if (!value_assigned) {
            allocator.free(parsed_value);
        }
    }

    try flushCurrentSyncRule(allocator, &config, &current_sync);
    return config;
}

fn flushCurrentSyncRule(
    allocator: Allocator,
    config: *ParsedConfig,
    current_sync: *?SyncRuleBuilder,
) !void {
    if (current_sync.* == null) return;

    var rule = current_sync.*.?;
    current_sync.* = null;
    errdefer rule.deinit(allocator);

    if (!rule.hasAnyField()) return;

    if (rule.source_table == null or rule.target_collection == null) {
        return error.InvalidConfig;
    }

    try config.sync_rules.append(allocator, .{
        .source_table = rule.source_table.?,
        .target_collection = rule.target_collection.?,
        .trigger_column = rule.trigger_column,
        .embedding_model = rule.embedding_model,
    });

    rule.source_table = null;
    rule.target_collection = null;
    rule.trigger_column = null;
    rule.embedding_model = null;
}

fn splitKeyValue(line: []const u8) ?KeyValue {
    var in_single = false;
    var in_double = false;
    var escaped = false;

    for (line, 0..) |ch, idx| {
        if (in_double) {
            if (escaped) {
                escaped = false;
                continue;
            }
            if (ch == '\\') {
                escaped = true;
                continue;
            }
            if (ch == '"') {
                in_double = false;
            }
            continue;
        }

        if (in_single) {
            if (ch == '\'') in_single = false;
            continue;
        }

        if (ch == '"') {
            in_double = true;
            continue;
        }
        if (ch == '\'') {
            in_single = true;
            continue;
        }

        if (ch == '=') {
            return .{
                .key = std.mem.trim(u8, line[0..idx], " \t\r"),
                .value = std.mem.trim(u8, line[idx + 1 ..], " \t\r"),
            };
        }
    }

    return null;
}

fn parseTableHeader(line: []const u8) ?TableHeader {
    if (line.len < 3 or line[0] != '[' or line[line.len - 1] != ']') return null;

    if (line.len >= 4 and line[1] == '[' and line[line.len - 2] == ']') {
        const name = std.mem.trim(u8, line[2 .. line.len - 2], " \t\r");
        if (name.len == 0) return null;
        return .{
            .is_array = true,
            .name = name,
        };
    }

    const name = std.mem.trim(u8, line[1 .. line.len - 1], " \t\r");
    if (name.len == 0) return null;
    return .{
        .is_array = false,
        .name = name,
    };
}

fn stripInlineComment(line: []const u8) []const u8 {
    var in_single = false;
    var in_double = false;
    var escaped = false;

    for (line, 0..) |ch, idx| {
        if (in_double) {
            if (escaped) {
                escaped = false;
                continue;
            }
            if (ch == '\\') {
                escaped = true;
                continue;
            }
            if (ch == '"') {
                in_double = false;
            }
            continue;
        }

        if (in_single) {
            if (ch == '\'') in_single = false;
            continue;
        }

        if (ch == '"') {
            in_double = true;
            continue;
        }
        if (ch == '\'') {
            in_single = true;
            continue;
        }
        if (ch == '#') {
            return line[0..idx];
        }
    }

    return line;
}

fn parseTomlStringLike(allocator: Allocator, raw: []const u8) ![]u8 {
    const value = std.mem.trim(u8, raw, " \t\r");
    if (value.len == 0) return error.InvalidConfig;

    if (value.len >= 2 and value[0] == '"' and value[value.len - 1] == '"') {
        return parseDoubleQuotedString(allocator, value[1 .. value.len - 1]);
    }

    if (value.len >= 2 and value[0] == '\'' and value[value.len - 1] == '\'') {
        return allocator.dupe(u8, value[1 .. value.len - 1]);
    }

    return allocator.dupe(u8, value);
}

fn parseDoubleQuotedString(allocator: Allocator, value: []const u8) ![]u8 {
    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(allocator);

    var i: usize = 0;
    while (i < value.len) : (i += 1) {
        const ch = value[i];
        if (ch != '\\') {
            try out.append(allocator, ch);
            continue;
        }

        if (i + 1 >= value.len) return error.InvalidConfig;
        i += 1;

        const esc = value[i];
        const decoded: u8 = switch (esc) {
            'n' => '\n',
            'r' => '\r',
            't' => '\t',
            '\\' => '\\',
            '"' => '"',
            else => esc,
        };
        try out.append(allocator, decoded);
    }

    return out.toOwnedSlice(allocator);
}

fn replaceOwnedField(allocator: Allocator, dest: *?[]u8, value: []u8) void {
    if (dest.*) |old| allocator.free(old);
    dest.* = value;
}

fn readFileAlloc(allocator: Allocator, path: []const u8, max_bytes: usize) ![]u8 {
    return std.Io.Dir.cwd().readFileAlloc(
        io_compat.runtimeIo(),
        path,
        allocator,
        std.Io.Limit.limited(max_bytes),
    );
}

fn writeFileAll(path: []const u8, data: []const u8) !void {
    try std.Io.Dir.cwd().writeFile(io_compat.runtimeIo(), .{
        .sub_path = path,
        .data = data,
    });
}

fn joinPath(allocator: Allocator, base: []const u8, leaf: []const u8) ![]u8 {
    if (base.len == 0 or std.mem.eql(u8, base, ".")) {
        return allocator.dupe(u8, leaf);
    }
    if (std.mem.endsWith(u8, base, "/")) {
        return std.fmt.allocPrint(allocator, "{s}{s}", .{ base, leaf });
    }
    return std.fmt.allocPrint(allocator, "{s}/{s}", .{ base, leaf });
}

fn formatSequence(allocator: Allocator, value: u32) ![]u8 {
    var digits_buf: [16]u8 = undefined;
    const digits = try std.fmt.bufPrint(&digits_buf, "{d}", .{value});

    if (digits.len >= 3) return allocator.dupe(u8, digits);

    var out = try allocator.alloc(u8, 3);
    @memset(out, '0');
    std.mem.copyForwards(u8, out[3 - digits.len ..], digits);
    return out;
}

fn parseLeadingSequence(name: []const u8) ?u32 {
    var end: usize = 0;
    while (end < name.len and std.ascii.isDigit(name[end])) : (end += 1) {}
    if (end == 0) return null;
    return std.fmt.parseInt(u32, name[0..end], 10) catch null;
}

fn findNextMigrationSequence(migrations_dir: []const u8) !u32 {
    const io_iface = io_compat.runtimeIo();
    var dir = std.Io.Dir.cwd().openDir(io_iface, migrations_dir, .{ .iterate = true }) catch |err| {
        if (err == error.FileNotFound) return 1;
        return err;
    };
    defer dir.close(io_iface);

    var max_sequence: u32 = 0;
    var iter = dir.iterate();
    while (try iter.next(io_iface)) |entry| {
        if (entry.kind != .file) continue;
        if (parseLeadingSequence(entry.name)) |seq| {
            if (seq > max_sequence) max_sequence = seq;
        }
    }

    if (max_sequence == std.math.maxInt(u32)) return error.Overflow;
    return max_sequence + 1;
}

fn isHybridProject(project_mode: ?[]const u8) bool {
    if (project_mode) |value| {
        return std.ascii.eqlIgnoreCase(std.mem.trim(u8, value, " \t\r"), "hybrid");
    }
    return false;
}

fn appendSqlStringLiteral(
    allocator: Allocator,
    out: *std.ArrayList(u8),
    value: []const u8,
) !void {
    try out.appendSlice(allocator, "'");
    for (value) |ch| {
        if (ch == '\'') {
            try out.appendSlice(allocator, "''");
        } else {
            try out.append(allocator, ch);
        }
    }
    try out.appendSlice(allocator, "'");
}

fn makeRuleNames(
    allocator: Allocator,
    source_table: []const u8,
) !struct { trigger_name: []u8, function_name: []u8 } {
    const safe_table = try toSafeIdentifier(allocator, source_table);
    defer allocator.free(safe_table);

    return .{
        .trigger_name = try std.fmt.allocPrint(allocator, "qail_sync_{s}", .{safe_table}),
        .function_name = try std.fmt.allocPrint(allocator, "_qail_{s}_notify", .{safe_table}),
    };
}

fn appendSyncRuleUp(
    allocator: Allocator,
    out: *std.ArrayList(u8),
    rule: *const SyncRule,
) !void {
    const names = try makeRuleNames(allocator, rule.source_table);
    defer allocator.free(names.trigger_name);
    defer allocator.free(names.function_name);

    const update_condition = if (rule.trigger_column) |column|
        try std.fmt.allocPrint(
            allocator,
            "TG_OP = 'UPDATE' and NEW.{s} is distinct from OLD.{s}",
            .{ column, column },
        )
    else
        try allocator.dupe(u8, "TG_OP = 'UPDATE'");
    defer allocator.free(update_condition);

    const fn_header = try std.fmt.allocPrint(
        allocator,
        "# Trigger function for {s} -> Qdrant sync\nfunction {s}() returns trigger {{\n",
        .{ rule.source_table, names.function_name },
    );
    defer allocator.free(fn_header);
    try out.appendSlice(allocator, fn_header);

    try out.appendSlice(allocator, "  # On INSERT: Always queue (new row = new embedding)\n");
    try out.appendSlice(allocator, "  if TG_OP = 'INSERT' {\n");
    try out.appendSlice(allocator, "    insert into _qail_queue (ref_table, ref_id, operation, payload)\n");
    try out.appendSlice(allocator, "    values (");
    try appendSqlStringLiteral(allocator, out, rule.source_table);
    try out.appendSlice(allocator, ", NEW.id::text, 'UPSERT', to_jsonb(NEW))\n");
    try out.appendSlice(allocator, "  }\n\n");

    const update_line = try std.fmt.allocPrint(
        allocator,
        "  # On UPDATE: Only queue if trigger column changed (saves CPU/API costs!)\n  if {s} {{\n",
        .{update_condition},
    );
    defer allocator.free(update_line);
    try out.appendSlice(allocator, update_line);
    try out.appendSlice(allocator, "    insert into _qail_queue (ref_table, ref_id, operation, payload)\n");
    try out.appendSlice(allocator, "    values (");
    try appendSqlStringLiteral(allocator, out, rule.source_table);
    try out.appendSlice(allocator, ", NEW.id::text, 'UPSERT', to_jsonb(NEW))\n");
    try out.appendSlice(allocator, "  }\n\n");

    try out.appendSlice(allocator, "  # On DELETE: Always queue (must remove from Qdrant)\n");
    try out.appendSlice(allocator, "  if TG_OP = 'DELETE' {\n");
    try out.appendSlice(allocator, "    insert into _qail_queue (ref_table, ref_id, operation, payload)\n");
    try out.appendSlice(allocator, "    values (");
    try appendSqlStringLiteral(allocator, out, rule.source_table);
    try out.appendSlice(allocator, ", OLD.id::text, 'DELETE', to_jsonb(OLD))\n");
    try out.appendSlice(allocator, "  }\n\n");

    try out.appendSlice(allocator, "  return coalesce(NEW, OLD)\n");
    try out.appendSlice(allocator, "}\n\n");

    const trigger_block = try std.fmt.allocPrint(
        allocator,
        "trigger {s}\n  after insert or update or delete on {s}\n  for each row execute {s}()\n\n",
        .{ names.trigger_name, rule.source_table, names.function_name },
    );
    defer allocator.free(trigger_block);
    try out.appendSlice(allocator, trigger_block);
}

fn appendSyncRuleDown(
    allocator: Allocator,
    out: *std.ArrayList(u8),
    rule: *const SyncRule,
) !void {
    const names = try makeRuleNames(allocator, rule.source_table);
    defer allocator.free(names.trigger_name);
    defer allocator.free(names.function_name);

    const block = try std.fmt.allocPrint(
        allocator,
        "drop trigger if exists {s} on {s}\ndrop function if exists {s}\n\n",
        .{ names.trigger_name, rule.source_table, names.function_name },
    );
    defer allocator.free(block);
    try out.appendSlice(allocator, block);
}

fn toSafeIdentifier(allocator: Allocator, input: []const u8) ![]u8 {
    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(allocator);

    for (input) |ch| {
        if (std.ascii.isAlphanumeric(ch) or ch == '_') {
            try out.append(allocator, std.ascii.toLower(ch));
        } else {
            if (out.items.len == 0 or out.items[out.items.len - 1] != '_') {
                try out.append(allocator, '_');
            }
        }
    }

    while (out.items.len > 0 and out.items[out.items.len - 1] == '_') {
        _ = out.pop();
    }

    if (out.items.len == 0) {
        try out.appendSlice(allocator, "sync");
    }
    if (std.ascii.isDigit(out.items[0])) {
        try out.insert(allocator, 0, '_');
    }

    return out.toOwnedSlice(allocator);
}

test "parse qail.toml extracts project mode and sync rules with comments" {
    const allocator = std.testing.allocator;
    const raw =
        \\# project config
        \\[project]
        \\mode = "hybrid" # inline comment
        \\
        \\[[sync]]
        \\source_table = "products"
        \\trigger_column = "description"
        \\target_collection = "products_search"
        \\embedding_model = "candle:bert-base" # keep this
        \\
        \\[[sync]]
        \\source_table = 'orders'
        \\target_collection = "orders_search"
    ;

    var cfg = try parseQailToml(allocator, raw);
    defer cfg.deinit(allocator);

    try std.testing.expect(cfg.project_mode != null);
    try std.testing.expectEqualStrings("hybrid", cfg.project_mode.?);
    try std.testing.expectEqual(@as(usize, 2), cfg.sync_rules.items.len);
    try std.testing.expectEqualStrings("products", cfg.sync_rules.items[0].source_table);
    try std.testing.expectEqualStrings("products_search", cfg.sync_rules.items[0].target_collection);
    try std.testing.expect(cfg.sync_rules.items[0].trigger_column != null);
    try std.testing.expectEqualStrings("description", cfg.sync_rules.items[0].trigger_column.?);
    try std.testing.expect(cfg.sync_rules.items[0].embedding_model != null);
    try std.testing.expectEqualStrings("candle:bert-base", cfg.sync_rules.items[0].embedding_model.?);
    try std.testing.expectEqualStrings("orders", cfg.sync_rules.items[1].source_table);
    try std.testing.expectEqualStrings("orders_search", cfg.sync_rules.items[1].target_collection);
}

test "parse qail.toml keeps hash inside quoted strings" {
    const allocator = std.testing.allocator;
    const raw =
        \\[project]
        \\mode = "hybrid"
        \\
        \\[[sync]]
        \\source_table = "catalog#2026"
        \\target_collection = "catalog#prod"
    ;

    var cfg = try parseQailToml(allocator, raw);
    defer cfg.deinit(allocator);

    try std.testing.expectEqual(@as(usize, 1), cfg.sync_rules.items.len);
    try std.testing.expectEqualStrings("catalog#2026", cfg.sync_rules.items[0].source_table);
    try std.testing.expectEqualStrings("catalog#prod", cfg.sync_rules.items[0].target_collection);
}

test "find next migration sequence from existing files" {
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    var root_buf: [std.fs.max_path_bytes]u8 = undefined;
    const root_len = try tmp.dir.realPath(std.testing.io, &root_buf);
    const root = root_buf[0..root_len];

    const migrations_dir = try joinPath(std.testing.allocator, root, "migrations");
    defer std.testing.allocator.free(migrations_dir);

    const io_iface = io_compat.runtimeIo();
    try std.Io.Dir.cwd().createDirPath(io_iface, migrations_dir);

    const mig1 = try joinPath(std.testing.allocator, migrations_dir, "001_init.up.qail");
    defer std.testing.allocator.free(mig1);
    const mig2 = try joinPath(std.testing.allocator, migrations_dir, "017_queue.down.qail");
    defer std.testing.allocator.free(mig2);
    const ignored = try joinPath(std.testing.allocator, migrations_dir, "notes.txt");
    defer std.testing.allocator.free(ignored);

    try std.Io.Dir.cwd().writeFile(io_iface, .{ .sub_path = mig1, .data = "" });
    try std.Io.Dir.cwd().writeFile(io_iface, .{ .sub_path = mig2, .data = "" });
    try std.Io.Dir.cwd().writeFile(io_iface, .{ .sub_path = ignored, .data = "" });

    const next = try findNextMigrationSequence(migrations_dir);
    try std.testing.expectEqual(@as(u32, 18), next);
}

test "generate sync triggers writes paired migration files with next sequence" {
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    var root_buf: [std.fs.max_path_bytes]u8 = undefined;
    const root_len = try tmp.dir.realPath(std.testing.io, &root_buf);
    const root = root_buf[0..root_len];

    const io_iface = io_compat.runtimeIo();

    const config_path = try joinPath(std.testing.allocator, root, "qail.toml");
    defer std.testing.allocator.free(config_path);

    const migrations_dir = try joinPath(std.testing.allocator, root, "migrations");
    defer std.testing.allocator.free(migrations_dir);
    try std.Io.Dir.cwd().createDirPath(io_iface, migrations_dir);

    const existing = try joinPath(std.testing.allocator, migrations_dir, "001_bootstrap.up.qail");
    defer std.testing.allocator.free(existing);
    try std.Io.Dir.cwd().writeFile(io_iface, .{ .sub_path = existing, .data = "# existing" });

    const config_raw =
        \\[project]
        \\mode = "hybrid"
        \\
        \\[[sync]]
        \\source_table = "products"
        \\trigger_column = "description"
        \\target_collection = "products_search"
        \\
        \\[[sync]]
        \\source_table = "public.orders"
        \\target_collection = "orders_search"
    ;

    try std.Io.Dir.cwd().writeFile(io_iface, .{
        .sub_path = config_path,
        .data = config_raw,
    });

    try generateSyncTriggersAt(std.testing.allocator, root);

    const up_path = try joinPath(std.testing.allocator, migrations_dir, "002_qail_sync_triggers.up.qail");
    defer std.testing.allocator.free(up_path);
    const down_path = try joinPath(std.testing.allocator, migrations_dir, "002_qail_sync_triggers.down.qail");
    defer std.testing.allocator.free(down_path);

    const up = try readFileAlloc(std.testing.allocator, up_path, 1024 * 1024);
    defer std.testing.allocator.free(up);
    const down = try readFileAlloc(std.testing.allocator, down_path, 1024 * 1024);
    defer std.testing.allocator.free(down);

    try std.testing.expect(std.mem.indexOf(u8, up, "function _qail_products_notify() returns trigger") != null);
    try std.testing.expect(std.mem.indexOf(u8, up, "trigger qail_sync_public_orders") != null);
    try std.testing.expect(std.mem.indexOf(u8, up, "NEW.description is distinct from OLD.description") != null);
    try std.testing.expect(std.mem.indexOf(u8, down, "drop trigger if exists qail_sync_products on products") != null);
    try std.testing.expect(std.mem.indexOf(u8, down, "drop function if exists _qail_public_orders_notify") != null);
}

test "generate sync triggers rejects non-hybrid project mode" {
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    var root_buf: [std.fs.max_path_bytes]u8 = undefined;
    const root_len = try tmp.dir.realPath(std.testing.io, &root_buf);
    const root = root_buf[0..root_len];

    const config_path = try joinPath(std.testing.allocator, root, "qail.toml");
    defer std.testing.allocator.free(config_path);

    const io_iface = io_compat.runtimeIo();
    try std.Io.Dir.cwd().writeFile(io_iface, .{
        .sub_path = config_path,
        .data =
        \\[project]
        \\mode = "database"
        \\
        \\[[sync]]
        \\source_table = "products"
        \\target_collection = "products_search"
        ,
    });

    try std.testing.expectError(
        error.InvalidProjectMode,
        generateSyncTriggersAt(std.testing.allocator, root),
    );
}
