#!/usr/bin/env python3
import argparse
import datetime as dt
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


def run(cmd, cwd=None, check=True):
    proc = subprocess.run(
        cmd,
        cwd=cwd,
        text=True,
        capture_output=True,
    )
    if check and proc.returncode != 0:
        msg = (
            f"command failed ({proc.returncode}): {' '.join(cmd)}\n"
            f"cwd: {cwd or os.getcwd()}\n"
            f"stdout:\n{proc.stdout}\n"
            f"stderr:\n{proc.stderr}\n"
        )
        raise RuntimeError(msg)
    return proc


def combined_output(proc):
    out = proc.stdout or ""
    err = proc.stderr or ""
    if out and err:
        return f"{out}\n{err}"
    return out or err


def extract_commands(help_text):
    commands = []
    seen = set()
    in_block = False

    for raw in help_text.splitlines():
        line = raw.rstrip("\n")
        stripped = line.strip()

        if stripped.startswith("Commands:") or stripped.startswith("Actions:"):
            in_block = True
            continue

        if not in_block:
            continue

        if stripped == "":
            break

        match = re.match(r"^(\s+)([a-zA-Z][a-zA-Z0-9_-]*)\b", line)
        if not match:
            continue

        indent = len(match.group(1).replace("\t", "    "))
        if indent < 2 or indent > 6:
            # Help descriptions often wrap with deep indentation; ignore those lines.
            continue

        name = match.group(2)
        if name not in seen:
            seen.add(name)
            commands.append(name)

    return commands


def safe_extract(cmd, cwd):
    try:
        proc = run(cmd, cwd=cwd, check=True)
        return extract_commands(combined_output(proc))
    except RuntimeError:
        return []


def gather_qail_rs_surface(qail_rs_dir):
    default_help = combined_output(run(
        ["cargo", "run", "-q", "-p", "qail", "--", "--help"],
        cwd=qail_rs_dir,
    ))
    full_help = combined_output(run(
        ["cargo", "run", "-q", "-p", "qail", "--features", "full", "--", "--help"],
        cwd=qail_rs_dir,
    ))

    out = {
        "top_level_default": extract_commands(default_help),
        "top_level_full": extract_commands(full_help),
        "migrate_actions": safe_extract(
            ["cargo", "run", "-q", "-p", "qail", "--", "migrate", "--help"],
            qail_rs_dir,
        ),
        "schema_actions": safe_extract(
            ["cargo", "run", "-q", "-p", "qail", "--", "schema", "--help"],
            qail_rs_dir,
        ),
        "branch_actions": safe_extract(
            ["cargo", "run", "-q", "-p", "qail", "--", "branch", "--help"],
            qail_rs_dir,
        ),
        "sync_actions": safe_extract(
            ["cargo", "run", "-q", "-p", "qail", "--features", "full", "--", "sync", "--help"],
            qail_rs_dir,
        ),
        "vector_actions": safe_extract(
            ["cargo", "run", "-q", "-p", "qail", "--features", "full", "--", "vector", "--help"],
            qail_rs_dir,
        ),
    }
    return out


def get_git_rev(qail_rs_dir):
    try:
        proc = run(["git", "-C", str(qail_rs_dir), "rev-parse", "--short", "HEAD"], check=True)
        return proc.stdout.strip()
    except RuntimeError:
        return "unknown"


def zig_array(name, values):
    lines = [f"pub const {name} = [_][]const u8{{"]
    for value in values:
        lines.append(f'    "{value}",')
    lines.append("};")
    return "\n".join(lines)


def write_surface_file(output_path, qail_rs_dir, surface):
    output_path.parent.mkdir(parents=True, exist_ok=True)
    generated_utc = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    source_rel = "cli/src/bin/qail.rs"
    source_rev = get_git_rev(qail_rs_dir)

    body = [
        "// Generated by scripts/cli_surface_codegen.py",
        f"// Generated: {generated_utc}",
        f'pub const qail_rs_source = "{source_rel}";',
        f'pub const qail_rs_rev = "{source_rev}";',
        "",
        zig_array("top_level_default", surface["top_level_default"]),
        "",
        zig_array("top_level_full", surface["top_level_full"]),
        "",
        zig_array("migrate_actions", surface["migrate_actions"]),
        "",
        zig_array("schema_actions", surface["schema_actions"]),
        "",
        zig_array("branch_actions", surface["branch_actions"]),
        "",
        zig_array("sync_actions", surface["sync_actions"]),
        "",
        zig_array("vector_actions", surface["vector_actions"]),
        "",
    ]
    output_path.write_text("\n".join(body), encoding="utf-8")


def parse_generated_surface(path):
    text = path.read_text(encoding="utf-8")
    names = [
        "top_level_default",
        "top_level_full",
        "migrate_actions",
        "schema_actions",
        "branch_actions",
        "sync_actions",
        "vector_actions",
    ]

    out = {}
    for name in names:
        match = re.search(
            rf"pub const {name} = \[_\]\[]const u8\{{(.*?)\}};",
            text,
            flags=re.S,
        )
        if not match:
            out[name] = []
            continue
        values = re.findall(r'"([^"]+)"', match.group(1))
        out[name] = values
    return out


def gather_qail_zig_surface(qail_bin):
    top_help = run([str(qail_bin), "--help"], check=False)
    migrate_help = run([str(qail_bin), "migrate", "--help"], check=False)
    branch_help = run([str(qail_bin), "branch", "--help"], check=False)
    schema_help = run([str(qail_bin), "schema", "--help"], check=False)
    sync_help = run([str(qail_bin), "sync", "--help"], check=False)
    vector_help = run([str(qail_bin), "vector", "--help"], check=False)

    return {
        "top_level": extract_commands(combined_output(top_help)),
        "migrate_actions": extract_commands(combined_output(migrate_help)),
        "branch_actions": extract_commands(combined_output(branch_help)),
        "schema_actions": extract_commands(combined_output(schema_help)),
        "sync_actions": extract_commands(combined_output(sync_help)),
        "vector_actions": extract_commands(combined_output(vector_help)),
        "exit_codes": {
            "top_level": top_help.returncode,
            "migrate": migrate_help.returncode,
            "branch": branch_help.returncode,
            "schema": schema_help.returncode,
            "sync": sync_help.returncode,
            "vector": vector_help.returncode,
        },
    }


def diff_lists(expected, actual):
    expected_set = set(expected)
    actual_set = set(actual)
    return sorted(expected_set - actual_set), sorted(actual_set - expected_set)


def check_help_side_effects(qail_bin):
    with tempfile.TemporaryDirectory(prefix="qail-help-sideeffects-") as td:
        td_path = Path(td)
        before = {str(p.relative_to(td_path)) for p in td_path.rglob("*")}
        run([str(qail_bin), "init", "--help"], cwd=td, check=False)
        run([str(qail_bin), "mig", "--help"], cwd=td, check=False)
        after = {str(p.relative_to(td_path)) for p in td_path.rglob("*")}
        created = sorted(after - before)
        return created


def print_parity_report(expected, actual, against, qail_zig_bin):
    top_expected = expected["top_level_full"] if against == "full" else expected["top_level_default"]
    top_missing, top_extra = diff_lists(top_expected, actual["top_level"])
    migrate_missing, migrate_extra = diff_lists(expected["migrate_actions"], actual["migrate_actions"])
    branch_missing, branch_extra = diff_lists(expected["branch_actions"], actual["branch_actions"])
    schema_missing, schema_extra = diff_lists(expected["schema_actions"], actual["schema_actions"])
    sync_missing, sync_extra = diff_lists(expected["sync_actions"], actual["sync_actions"])
    vector_missing, vector_extra = diff_lists(expected["vector_actions"], actual["vector_actions"])

    print(f"CLI parity against qail.rs ({against})")
    print(f"  top-level: {len(actual['top_level'])}/{len(top_expected)}")
    print(f"  migrate actions: {len(actual['migrate_actions'])}/{len(expected['migrate_actions'])}")
    print(f"  branch actions: {len(actual['branch_actions'])}/{len(expected['branch_actions'])}")
    print(f"  schema actions: {len(actual['schema_actions'])}/{len(expected['schema_actions'])}")
    print(f"  sync actions: {len(actual['sync_actions'])}/{len(expected['sync_actions'])}")
    print(f"  vector actions: {len(actual['vector_actions'])}/{len(expected['vector_actions'])}")

    def show(label, missing, extra):
        if not missing and not extra:
            print(f"  {label}: OK")
            return
        print(f"  {label}:")
        if missing:
            print(f"    missing: {', '.join(missing)}")
        if extra:
            print(f"    extra: {', '.join(extra)}")

    show("top-level", top_missing, top_extra)
    show("migrate", migrate_missing, migrate_extra)
    show("branch", branch_missing, branch_extra)
    show("schema", schema_missing, schema_extra)
    show("sync", sync_missing, sync_extra)
    show("vector", vector_missing, vector_extra)

    print("  qail-zig help exit codes:")
    for key, value in actual["exit_codes"].items():
        print(f"    {key}: {value}")

    side_effects = check_help_side_effects(qail_bin=qail_zig_bin)
    if side_effects:
        print("  help side-effects detected (unexpected files):")
        for entry in side_effects:
            print(f"    {entry}")
    else:
        print("  help side-effects: none")

    return {
        "top_missing": top_missing,
        "migrate_missing": migrate_missing,
        "branch_missing": branch_missing,
        "schema_missing": schema_missing,
        "sync_missing": sync_missing,
        "vector_missing": vector_missing,
        "help_side_effects": side_effects,
    }


def default_paths():
    root = Path(__file__).resolve().parents[1]
    qail_rs = Path(os.environ.get("QAIL_RS_DIR", root.parent / "qail.rs"))
    output = root / "src" / "cli" / "generated" / "rs_cli_surface.gen.zig"
    qail_zig_bin = root / "zig-out" / "bin" / "qail"
    return root, qail_rs, output, qail_zig_bin


def cmd_regen(args):
    surface = gather_qail_rs_surface(args.qail_rs)
    write_surface_file(args.output, args.qail_rs, surface)
    print(f"regenerated: {args.output}")


def cmd_parity(args):
    expected = parse_generated_surface(args.generated)
    actual = gather_qail_zig_surface(args.qail_zig_bin)
    report = print_parity_report(expected, actual, args.against, args.qail_zig_bin)
    missing_any = any(
        [
            report["top_missing"],
            report["migrate_missing"],
            report["branch_missing"],
            report["schema_missing"],
            report["sync_missing"],
            report["vector_missing"],
            report["help_side_effects"],
        ]
    )
    if args.strict and missing_any:
        return 1
    return 0


def cmd_sync_check(args):
    if not args.generated.exists():
        print(f"error: generated surface file missing: {args.generated}", file=sys.stderr)
        return 2

    with tempfile.TemporaryDirectory(prefix="qail-cli-surface-sync-") as td:
        td_path = Path(td) / args.generated.name
        shutil.copy2(args.generated, td_path)
        surface = gather_qail_rs_surface(args.qail_rs)
        write_surface_file(args.generated, args.qail_rs, surface)

        before = td_path.read_text(encoding="utf-8")
        after = args.generated.read_text(encoding="utf-8")

        before_norm = re.sub(r"^// Generated: .*$", "", before, flags=re.M)
        after_norm = re.sub(r"^// Generated: .*$", "", after, flags=re.M)
        if before_norm != after_norm:
            print("CLI surface file is out of date.", file=sys.stderr)
            print(
                f"run: ./scripts/regenerate_cli_surface.sh {args.qail_rs}",
                file=sys.stderr,
            )
            return 1

    print("cli surface sync check passed")
    return 0


def parse_args():
    root, default_rs, default_output, default_qail_bin = default_paths()

    parser = argparse.ArgumentParser(description="qail.rs -> qail-zig CLI surface tooling")
    sub = parser.add_subparsers(dest="mode", required=True)

    regen = sub.add_parser("regen", help="Regenerate rs_cli_surface.gen.zig from qail.rs help output")
    regen.add_argument("--qail-rs", type=Path, default=default_rs)
    regen.add_argument("--output", type=Path, default=default_output)
    regen.set_defaults(fn=cmd_regen)

    sync_check = sub.add_parser("sync-check", help="Check generated CLI surface is in sync with qail.rs")
    sync_check.add_argument("--qail-rs", type=Path, default=default_rs)
    sync_check.add_argument("--generated", type=Path, default=default_output)
    sync_check.set_defaults(fn=cmd_sync_check)

    parity = sub.add_parser("parity", help="Compare qail-zig CLI surface against generated qail.rs surface")
    parity.add_argument("--generated", type=Path, default=default_output)
    parity.add_argument("--qail-zig-bin", type=Path, default=default_qail_bin)
    parity.add_argument("--against", choices=["default", "full"], default="full")
    parity.add_argument("--strict", action="store_true")
    parity.set_defaults(fn=cmd_parity)

    return parser.parse_args(), root


if __name__ == "__main__":
    args_namespace, _root = parse_args()
    try:
        exit_code = args_namespace.fn(args_namespace)
    except RuntimeError as exc:
        print(str(exc), file=sys.stderr)
        exit_code = 1
    sys.exit(exit_code)
